using Microsoft.EntityFrameworkCore;
using RentTracker.Web.Models;

namespace RentTracker.Web.Data;

/// <summary>
/// Entity Framework database context for RentTracker.
/// Configures SQLite with optimizations for single-developer maintenance.
/// </summary>
public class RentTrackerDbContext : DbContext
{
    public RentTrackerDbContext(DbContextOptions<RentTrackerDbContext> options)
        : base(options)
    {
    }

    public DbSet<User> Users => Set<User>();
    public DbSet<Property> Properties => Set<Property>();
    public DbSet<PropertyUnit> PropertyUnits => Set<PropertyUnit>();
    public DbSet<Lease> Leases => Set<Lease>();
    public DbSet<Payment> Payments => Set<Payment>();
    public DbSet<PaymentAudit> PaymentAudits => Set<PaymentAudit>();
    public DbSet<PropertyPriceHistory> PropertyPriceHistory => Set<PropertyPriceHistory>();
    public DbSet<WhatsAppSettings> WhatsAppSettings => Set<WhatsAppSettings>();
    public DbSet<NotificationLog> NotificationLogs => Set<NotificationLog>();
    public DbSet<PushSubscription> PushSubscriptions => Set<PushSubscription>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // User configuration
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(u => u.Username).IsUnique();
            entity.HasIndex(u => u.Email).IsUnique();
            entity.Property(u => u.Username).HasMaxLength(50);
            entity.Property(u => u.Email).HasMaxLength(200);
            entity.Property(u => u.FullName).HasMaxLength(100);
            entity.Property(u => u.Role).HasMaxLength(100);
            entity.Property(u => u.PhoneNumber).HasMaxLength(20);
        });

        // Property configuration
        modelBuilder.Entity<Property>(entity =>
        {
            entity.Property(p => p.Name).HasMaxLength(200);
            entity.Property(p => p.Location).HasMaxLength(500);
            entity.Property(p => p.CurrentPrice).HasPrecision(18, 2);
            entity.Property(p => p.CurrentWarranty).HasPrecision(18, 2);
            entity.Property(p => p.IsPrivate).HasDefaultValue(false);
            
            entity.HasOne(p => p.Owner)
                .WithMany(u => u.OwnedProperties)
                .HasForeignKey(p => p.OwnerId)
                .OnDelete(DeleteBehavior.SetNull);
            
            entity.HasOne(p => p.LastEditedBy)
                .WithMany(u => u.LastEditedProperties)
                .HasForeignKey(p => p.LastEditedById)
                .OnDelete(DeleteBehavior.SetNull);
        });

        // PropertyUnit configuration
        modelBuilder.Entity<PropertyUnit>(entity =>
        {
            entity.Property(u => u.Name).HasMaxLength(100);
            entity.Property(u => u.Price).HasPrecision(18, 2);
            entity.Property(u => u.Warranty).HasPrecision(18, 2);
            
            entity.HasOne(u => u.Property)
                .WithMany(p => p.Units)
                .HasForeignKey(u => u.PropertyId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Lease configuration
        modelBuilder.Entity<Lease>(entity =>
        {
            entity.Property(l => l.Status).HasMaxLength(50);
            entity.Property(l => l.AgreedPrice).HasPrecision(18, 2);
            entity.Property(l => l.AgreedWarranty).HasPrecision(18, 2);
            entity.Property(l => l.TerminationReason).HasMaxLength(500);
            entity.Property(l => l.PaymentDueDay).HasDefaultValue(1);
            
            entity.HasOne(l => l.Property)
                .WithMany(p => p.Leases)
                .HasForeignKey(l => l.PropertyId)
                .OnDelete(DeleteBehavior.Restrict);
            
            entity.HasOne(l => l.PropertyUnit)
                .WithMany(u => u.Leases)
                .HasForeignKey(l => l.PropertyUnitId)
                .OnDelete(DeleteBehavior.Restrict);
            
            entity.HasOne(l => l.Tenant)
                .WithMany(u => u.Leases)
                .HasForeignKey(l => l.TenantId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Payment configuration
        modelBuilder.Entity<Payment>(entity =>
        {
            entity.Property(p => p.Amount).HasPrecision(18, 2);
            entity.Property(p => p.Currency).HasMaxLength(3);
            entity.Property(p => p.Status).HasMaxLength(50);
            entity.Property(p => p.Notes).HasMaxLength(200);
            
            entity.HasOne(p => p.Lease)
                .WithMany(l => l.Payments)
                .HasForeignKey(p => p.LeaseId)
                .OnDelete(DeleteBehavior.Cascade);

            // Backstop against the auto-generator racing a manual create: at most one
            // auto-generated row per lease + period. Manual rows are left unconstrained.
            entity.HasIndex(p => new { p.LeaseId, p.ForPeriod })
                .IsUnique()
                .HasFilter("[IsAutoGenerated] = 1");
        });

        // PaymentAudit configuration
        modelBuilder.Entity<PaymentAudit>(entity =>
        {
            entity.Property(a => a.Amount).HasPrecision(18, 2);
            entity.Property(a => a.Currency).HasMaxLength(3);
            entity.Property(a => a.Status).HasMaxLength(50);
            entity.Property(a => a.Notes).HasMaxLength(200);

            entity.HasIndex(a => a.PaymentId);

            entity.HasOne(a => a.Payment)
                .WithMany(p => p.AuditEntries)
                .HasForeignKey(a => a.PaymentId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // PropertyPriceHistory configuration
        modelBuilder.Entity<PropertyPriceHistory>(entity =>
        {
            entity.Property(h => h.Price).HasPrecision(18, 2);
            entity.Property(h => h.Warranty).HasPrecision(18, 2);
            
            entity.HasOne(h => h.Property)
                .WithMany(p => p.PriceHistory)
                .HasForeignKey(h => h.PropertyId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // WhatsAppSettings configuration
        modelBuilder.Entity<WhatsAppSettings>(entity =>
        {
            entity.Property(s => s.Provider).HasMaxLength(50);
            entity.Property(s => s.AccessToken).HasMaxLength(500);
            entity.Property(s => s.PhoneNumberId).HasMaxLength(100);
            entity.Property(s => s.DryRunPhoneNumber).HasMaxLength(20);
            entity.Property(s => s.BusinessAccountId).HasMaxLength(100);
            entity.Property(s => s.VerifyToken).HasMaxLength(200);
            entity.Property(s => s.TemplateLanguage).HasMaxLength(10).HasDefaultValue("en");
            entity.Property(s => s.TimeZoneOffset).HasDefaultValue(-4);
        });

        // NotificationLog configuration
        modelBuilder.Entity<NotificationLog>(entity =>
        {
            entity.Property(n => n.Type).HasMaxLength(50);
            entity.Property(n => n.RecipientRole).HasMaxLength(50);
            entity.Property(n => n.RecipientPhoneNumber).HasMaxLength(20);
            entity.Property(n => n.MessageContent).HasMaxLength(1000);
            entity.Property(n => n.Status).HasMaxLength(20);
            entity.Property(n => n.ErrorMessage).HasMaxLength(500);

            entity.HasOne(n => n.Lease)
                .WithMany()
                .HasForeignKey(n => n.LeaseId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired(false);

            entity.HasOne(n => n.RecipientUser)
                .WithMany()
                .HasForeignKey(n => n.RecipientUserId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired(false);
        });

        // PushSubscription configuration
        modelBuilder.Entity<PushSubscription>(entity =>
        {
            entity.Property(s => s.Endpoint).HasMaxLength(500);
            entity.Property(s => s.P256dh).HasMaxLength(200);
            entity.Property(s => s.Auth).HasMaxLength(200);

            entity.HasIndex(s => s.UserId);
            entity.HasIndex(s => s.Endpoint).IsUnique();

            entity.HasOne(s => s.User)
                .WithMany()
                .HasForeignKey(s => s.UserId)
                .OnDelete(DeleteBehavior.Cascade);
        });
    }
}
